# Generated by Django 3.0.7 on 2021-01-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=128, unique=True, verbose_name='厂商名称')),
                ('firm_owner', models.CharField(max_length=128, verbose_name='厂商联系人')),
                ('firm_phone', models.IntegerField(verbose_name='厂商联系电话')),
            ],
            options={
                'verbose_name': '厂商列表',
                'verbose_name_plural': '厂商列表',
                'db_table': 'table_firm_list',
            },
        ),
    ]
