# Generated by Django 3.0.7 on 2021-01-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicinfo', '0002_firmlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmlist',
            name='firm_phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='厂商联系电话'),
        ),
    ]
