# Generated by Django 3.0.7 on 2021-01-07 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicinfo', '0005_secret'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Secret',
        ),
    ]
