# Generated by Django 3.0.7 on 2021-01-06 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publicinfo', '0004_envlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppResourcesClass',
            fields=[
                ('app_short', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='系统简称')),
                ('app_en_full', models.CharField(blank=True, max_length=128, null=True, verbose_name='系统英文全称')),
                ('app_ch_full', models.CharField(blank=True, max_length=128, null=True, verbose_name='系统中文全称')),
                ('app_explain', models.TextField(blank=True, null=True, verbose_name='系统简介')),
                ('business_dept', models.CharField(blank=True, max_length=128, null=True, verbose_name='业务负责部门')),
                ('pm', models.CharField(blank=True, max_length=128, null=True, verbose_name='产品经理')),
                ('level', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=8, null=True, verbose_name='系统等级')),
                ('status', models.CharField(blank=True, max_length=64, null=True, verbose_name='状态')),
                ('dev_mode', models.CharField(blank=True, max_length=128, null=True, verbose_name='建设方式')),
                ('service_time', models.CharField(blank=True, max_length=256, null=True, verbose_name='服务窗口')),
                ('dev_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publicinfo.ProjectGroupList', verbose_name='开发项目组')),
                ('firm_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publicinfo.FirmList', verbose_name='厂商名称')),
            ],
            options={
                'verbose_name': '应用系统清单',
                'verbose_name_plural': '应用系统清单',
                'db_table': 'table_app_list',
            },
        ),
    ]
