# Generated by Django 3.0.7 on 2021-01-07 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicinfo', '0004_envlist'),
        ('appinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppResourcesClass',
            new_name='SystemResourcesClass',
        ),
        migrations.AlterModelTable(
            name='systemresourcesclass',
            table='table_system_list',
        ),
    ]
