# Generated by Django 3.0.7 on 2021-01-07 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appinfo', '0003_auto_20210107_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSystemList',
            fields=[
                ('subapp_short', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='子系统简称')),
                ('subapp_en_full', models.CharField(blank=True, max_length=128, null=True, verbose_name='子系统英文全称')),
                ('subapp_ch_full', models.CharField(blank=True, max_length=128, null=True, verbose_name='子系统中文全称')),
                ('subapp_id', models.IntegerField(blank=True, null=True, verbose_name='子系统ID')),
                ('subapp_explain', models.TextField(blank=True, null=True, verbose_name='子系统简介')),
                ('dev_a', models.CharField(blank=True, max_length=128, null=True, verbose_name='开发A角')),
                ('dev_a_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='开发A角邮箱')),
                ('dev_a_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='开发A角电话')),
                ('dev_b', models.CharField(blank=True, max_length=128, null=True, verbose_name='开发B角')),
                ('dev_b_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='开发B角邮箱')),
                ('dev_b_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='开发B角电话')),
                ('dev_owner', models.CharField(blank=True, max_length=128, null=True, verbose_name='开发升级责任人')),
                ('test_owner', models.CharField(blank=True, max_length=128, null=True, verbose_name='测试负责人')),
                ('ops_a', models.CharField(blank=True, max_length=128, null=True, verbose_name='运维A角')),
                ('ops_a_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='运维A角邮箱')),
                ('ops_a_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='运维A角电话')),
                ('ops_b', models.CharField(blank=True, max_length=128, null=True, verbose_name='运维B角')),
                ('ops_b_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='运维B角邮箱')),
                ('ops_b_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='运维B角电话')),
                ('ops_owner', models.CharField(blank=True, max_length=128, null=True, verbose_name='运维升级责任人')),
                ('online_time', models.DateField(blank=True, null=True, verbose_name='上线时间')),
                ('dev_language', models.CharField(blank=True, max_length=128, null=True, verbose_name='开发语言')),
                ('frame', models.CharField(blank=True, max_length=128, null=True, verbose_name='框架')),
                ('middleware', models.CharField(blank=True, max_length=128, null=True, verbose_name='中间件产品')),
                ('deploy_location', models.IntegerField(blank=True, choices=[(0, '行内'), (1, '行外')], null=True, verbose_name='部署位置')),
                ('app_short', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appinfo.SystemList', verbose_name='所属系统简称')),
            ],
            options={
                'verbose_name': '子系统清单',
                'verbose_name_plural': '子系统清单',
                'db_table': 'table_subsystem_list',
            },
        ),
    ]
