# Generated by Django 3.0.7 on 2021-01-08 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appinfo', '0005_subsystemdetails'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subsystemdetails',
            table='table_subsys_details',
        ),
    ]
