# Generated by Django 3.0.7 on 2021-01-08 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appinfo', '0006_auto_20210108_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setid', models.CharField(max_length=128, verbose_name='所属set')),
                ('vip', models.GenericIPAddressField(verbose_name='VIP')),
                ('vport', models.IntegerField(verbose_name='TGW端口')),
                ('master_rip', models.CharField(max_length=128, verbose_name='主节点IP')),
                ('master_rport', models.CharField(max_length=128, verbose_name='主节点端口')),
                ('slave_rip', models.CharField(max_length=128, verbose_name='备节点IP')),
                ('slave_rport', models.CharField(max_length=128, verbose_name='备节点端口')),
                ('db_name', models.CharField(max_length=128, verbose_name='数据库名称')),
                ('dba_owner', models.CharField(blank=True, max_length=128, null=True, verbose_name='运维负责人')),
                ('dba_email', models.CharField(blank=True, max_length=128, null=True, verbose_name='运维负责人邮箱')),
                ('dba_phone', models.CharField(blank=True, max_length=128, null=True, verbose_name='运维负责人电话')),
                ('app_short', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appinfo.SystemList', verbose_name='所属系统简称')),
                ('subapp_short', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appinfo.SubSystemList', verbose_name='所属子系统简称')),
            ],
            options={
                'verbose_name': '数据库资源详情',
                'verbose_name_plural': '数据库资源详情',
                'db_table': 'table_db_details',
                'unique_together': {('vip', 'vport')},
            },
        ),
    ]
