# Generated by Django 3.0.7 on 2021-01-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinfo', '0007_databasedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='systemlist',
            name='firm_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='厂商名称'),
        ),
    ]
