# Generated by Django 3.0.7 on 2021-01-19 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appinfo', '0008_auto_20210108_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configdetails',
            options={'verbose_name': '配置文件信息', 'verbose_name_plural': '配置文件信息'},
        ),
        migrations.AddField(
            model_name='configdetails',
            name='app_short',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appinfo.SystemList', verbose_name='所属系统简称'),
        ),
        migrations.AddField(
            model_name='configdetails',
            name='config_md5',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='配置项MD5值'),
        ),
        migrations.AddField(
            model_name='configdetails',
            name='config_path',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='配置文件路径'),
        ),
        migrations.AddField(
            model_name='configdetails',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址'),
        ),
        migrations.AddField(
            model_name='configdetails',
            name='lines',
            field=models.IntegerField(blank=True, null=True, verbose_name='行号'),
        ),
        migrations.AddField(
            model_name='configdetails',
            name='new_conf',
            field=models.TextField(blank=True, null=True, verbose_name='新配置'),
        ),
        migrations.AddField(
            model_name='configdetails',
            name='old_conf',
            field=models.TextField(blank=True, null=True, verbose_name='旧配置'),
        ),
        migrations.AddField(
            model_name='configdetails',
            name='subapp_short',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appinfo.SubSystemList', verbose_name='所属子系统简称'),
        ),
        migrations.AlterModelTable(
            name='configdetails',
            table='table_config_details',
        ),
    ]
