"""
Django settings for onebankCMDB project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'fpiy!^nj=0jhphy7ei54t&5o)ay!&)ih95&+9r+h#6i#oh(6k-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',#渲染表格
    'import_export',#导入导出模块
    'rest_framework',
    'django_filters',
    'publicinfo',
    'appinfo',
]

#默认值为False。数据导入中使用数据库事务，以确保安全。
IMPORT_EXPORT_USE_TRANSACTIONS = True

REST_FRAMEWORK = {
 'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
# 新版drf schema_class默认用的是rest_framework.schemas.openapi.AutoSchema
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'oneCMDB.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'oneCMDB.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'cmdb',
        'HOST': '192.168.220.129',
        'PORT': 3306,
        'USER': 'root',
        'PASSWORD': 'Root@123',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, "static"),
# ]

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

import time

SIMPLEUI_CONFIG = {
    'system_keep': False,
    'menu_display': ['基础信息', '应用系统资源', '服务器资源', '网络资源', '权限认证'],  # 开启排序和过滤功能, 不填此字段为默认排序和全部显示, 空列表[] 为全部不显示.
    'dynamic': True,  # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时动态展示菜单内容
    'menus': [{
        'name': '基础信息',
        'icon': 'fas fa-surprise',
        'models': [{
            'name': '项目组列表',
            'icon': 'fas fa-surprise',
            'url': 'publicinfo/projectgrouplist/'
        }, {
            'name': '厂商列表',
            'icon': 'fas fa-surprise',
            'url': 'publicinfo/firmlist/'
        }, {
            'name': '环境列表',
            'icon': 'fas fa-surprise',
            'url': 'publicinfo/envlist/'
        }]
    }, {
        'name': '应用系统资源',
        'icon': 'fas fa-surprise',
        'models': [{
            'name': '应用系统清单',
            'icon': 'fas fa-surprise',
            'url': 'appinfo/systemlist/'
        },{
            'name': '子系统清单',
            'icon': 'fas fa-surprise',
            'url': 'appinfo/subsystemlist/'
        },{
            'name': '子系统资源详情',
            'icon': 'fas fa-surprise',
            'url': 'appinfo/subsystemdetails/'
        },{
            'name': '数据库资源详情',
            'icon': 'fas fa-surprise',
            'url': 'appinfo/databasedetails/'
        },{
            'name': '配置文件信息',
            'icon': 'fas fa-surprise',
            'url': 'appinfo/configdetails/'
        }]
    }, {
        'name': '服务器资源',
        'icon': 'fas fa-surprise',
        'models': [{
            'name': '机柜信息表',
            'url': '',
            'icon': 'fas fa-surprise'
        }, {
            'name': '物理设备资源详情',
            'url': '',
            'icon': 'fas fa-surprise'
        }, {
            'name': '虚拟机资源',
            'url': '',
            'icon': 'fas fa-surprise'
        }]
    }, {
        'name': '网络资源',
        'icon': 'fas fa-surprise',
        'models': [{
            'name': '网络设备',
            'url': '',
            'icon': 'fas fa-surprise'
        },{
            'name': 'TGW信息',
            'url': '',
            'icon': 'fas fa-surprise'
        },{
            'name': '互联网线路',
            'url': '',
            'icon': 'fas fa-surprise'
        },{
            'name': '专线线路',
            'url': '',
            'icon': 'fas fa-surprise'
        }]
    }, {'app': 'auth',
        'name': '权限认证',
        'icon': 'fas fa-surprise',
        'models': [{
            'name': '用户',
            'url': 'auth/user/',
            'icon': 'fas fa-surprise'
        },{
            'name': '组',
            'url': 'auth/group/',
            'icon': 'fas fa-surprise'
        }]
    }]
}

# 隐藏右上角服务器信息
SIMPLEUI_HOME_INFO = False

# SIMPLEUI不收集分析信息
SIMPLEUI_ANALYSIS = False

# 以脱机模式加载静态资源
SIMPLEUI_STATIC_OFFLINE = True
